# Generated by Django 4.0.2 on 2022-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleNo', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=25)),
                ('model', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
