# Generated by Django 4.0.2 on 2022-02-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=25)),
                ('model', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('vehicle_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testphase.vehicle')),
            ],
        ),
    ]
