# Generated by Django 4.0.2 on 2022-02-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testphase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_no',
            new_name='vehicleNo',
        ),
    ]
