# Generated by Django 4.0.2 on 2022-02-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testphase', '0002_rename_vehicleno_vehicle_vehicle_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('vehicle_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testphase.vehicle')),
            ],
        ),
    ]
