# Generated by Django 4.0.2 on 2022-02-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testphase', '0002_rename_vehicle_no_vehicle_vehicleno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicleNo',
            new_name='vehicle_no',
        ),
    ]
